---
- hosts: sudoers 

  vars_files:
    - vars.yml

  tasks:
    - name: 'Delete sudoers tmp file'
      command: rm -rf /etc/sudoers.tmp

    - name: 'Copy sudoers file for safety'
      command: cp -f /etc/sudoers /etc/sudoers.tmp

    - name: 'Create sudoers file backup - "{{ ansible_date_time.date }}"'
      command: cp -f /etc/sudoers /etc/sudoers."{{ ansible_date_time.date }}"

    - name: 'Add users/groups to sudoers tmp file'
      lineinfile: dest=/etc/sudoers.tmp state=present regexp='^{{ item.0 }}' line='{{ item.0 }}      {{ item.1 }}'
      with_together:
        - "{{ user }}"
        - "{{ privs }}"

    - name: 'Make sure ssh-agent works via sudo'
      lineinfile: dest=/etc/sudoers.tmp state=present regexp='^Defaults env_keep\+\=SSH_AUTH_SOCK' line='Defaults env_keep+=SSH_AUTH_SOCK'

    - name: 'Final sudoers file check'
      shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
